import Link from "next/link";
import Image from "next/image";
import { redirect } from "next/navigation";
import { ArrowRight, FileText, Link2, MailCheck, MousePointerClick, ShieldCheck, Bot } from "lucide-react";
import { userId } from "@/lib/auth";
import { Brand } from "@/components/brand";
import { StageTrack } from "@/components/status";

export default async function Landing() {
  if (await userId()) redirect("/dashboard");
  return (
    <main className="paper-grid min-h-screen">
      <div className="mx-auto max-w-6xl px-6">
        <header className="flex items-center justify-between py-6">
          <Brand />
          <nav className="flex items-center gap-2 text-sm"><Link href="/sign-in" className="btn-ghost">Sign in</Link><Link href="/sign-up" className="btn-primary">Create account</Link></nav>
        </header>

        <section className="grid items-center gap-12 py-16 lg:grid-cols-[1.05fr_1fr] lg:py-24">
          <div>
            <p className="eyebrow">For Greenhouse, Lever and Ashby job posts</p>
            <h1 className="serif mt-4 text-5xl leading-[1.02] tracking-tight md:text-6xl">Paste a job link.<br />Get a reviewed application, not a guess.</h1>
            <p className="mt-6 max-w-lg text-lg leading-relaxed text-muted">Auto Apply rewrites your resume for each role using only facts from your own profile, answers the form with what it knows about you, emails you the rest, and fills the real form. You press Submit.</p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link href="/sign-up" className="btn-primary px-5 py-2.5 text-base">Start with your resume <ArrowRight size={16} /></Link>
              <Link href="/sign-in" className="btn-ghost px-5 py-2.5 text-base">I have an account</Link>
            </div>
            <p className="mt-4 text-sm text-muted">Free while in beta. Nothing is submitted without your explicit approval.</p>
          </div>
          <div className="relative">
            <div className="panel overflow-hidden shadow-[0_30px_80px_-40px_rgba(22,24,29,0.45)]">
              <div className="flex items-center justify-between border-b border-line px-5 py-3">
                <div><div className="text-sm font-medium">Cloudflare: Software Engineer, Platforms</div><div className="text-xs text-muted">Hybrid · Greenhouse</div></div>
                <span className="rounded-full bg-signal-soft px-2.5 py-0.5 text-xs font-medium text-signal">Awaiting your Submit</span>
              </div>
              <div className="px-5 py-3"><StageTrack status="filled" needsDetails={false} /></div>
              <div className="relative h-[380px] overflow-hidden border-t border-line bg-tint">
                <Image src="/sample-resume.png" alt="A tailored one-page resume generated by Auto Apply" width={1200} height={1553} className="absolute left-1/2 top-4 w-[78%] -translate-x-1/2 rounded-sm shadow-lg" priority />
              </div>
            </div>
            <div className="panel absolute -bottom-6 -left-6 hidden w-64 items-start gap-3 p-4 shadow-lg md:flex">
              <MailCheck className="mt-0.5 shrink-0 text-go" size={18} />
              <div className="text-sm"><div className="font-medium">Resume ready</div><div className="text-muted">2 questions need you: notice period, why this company.</div></div>
            </div>
          </div>
        </section>

        <section className="grid gap-6 py-16 md:grid-cols-3">
          {[
            [Link2, "Paste a link", "The posting is read from the board's own API, including every form question it asks."],
            [FileText, "A resume written for that role", "One page, your layout, your facts. Every number is checked against your profile before it renders."],
            [MailCheck, "Known answers filled, the rest asked", "Name, links, location, sponsorship and relocation come from your Answers page. Open questions arrive by email."],
            [Bot, "The form is filled on your machine", "A small runner opens the real form in a browser window, attaches the PDF, and stops with a screenshot."],
            [MousePointerClick, "You press Submit", "Approve in the app, then submit. Nothing goes out earlier."],
            [ShieldCheck, "Your data stays yours", "Your profile, answers and applications live in your account. Delete any of it any time."]
          ].map(([Icon, title, body]) => {
            const I = Icon as React.ComponentType<{ size?: number; className?: string }>;
            return <div key={title as string} className="panel-pad"><I size={20} className="text-brand" /><h3 className="mt-4 font-medium">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-muted">{body as string}</p></div>;
          })}
        </section>

        <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-line py-8 text-sm text-muted"><Brand /><span>Built for people applying to a lot of jobs and tired of retyping their own name.</span></footer>
      </div>
    </main>
  );
}
